# Generated by Django 5.2.3 on 2025-07-13 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_payments_paid_course_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payments",
            name="date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата оплаты"),
        ),
    ]
