# Generated by Django 5.2.3 on 2025-07-27 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_payments_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="last_login",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Дата последней авторизации"),
        ),
    ]
