# Generated by Django 5.2.3 on 2025-07-05 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0005_course_is_subscribe_alter_lesson_video_link_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscribe",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses",
                to="materials.course",
                verbose_name="Название курса",
            ),
        ),
    ]
