# Generated by Django 5.2.3 on 2025-07-13 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0006_alter_subscribe_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="amount",
            field=models.PositiveIntegerField(
                blank=True, help_text="Укажите стоимость", null=True, verbose_name="Стоимость"
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="is_paid",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lesson",
            name="amount",
            field=models.PositiveIntegerField(
                blank=True, help_text="Укажите стоимость", null=True, verbose_name="Стоимость"
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="is_paid",
            field=models.BooleanField(default=False),
        ),
    ]
