# Generated by Django 5.2.3 on 2025-07-22 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0007_course_amount_course_is_paid_lesson_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="stripe_product_id",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="ID курса на страйпе"),
        ),
        migrations.AddField(
            model_name="lesson",
            name="stripe_product_id",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="ID урока на страйпе"),
        ),
    ]
