# Generated by Django 5.2.3 on 2025-07-27 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0007_course_updated_at"),
        ("materials", "0008_course_stripe_product_id_lesson_stripe_product_id"),
    ]

    operations = []
